"""Plain-text rendering of the same issue.

Kept deliberately simple and hard-wrapped at 78 columns so it reads correctly in a
terminal, a plain-text email part, or a diff.
"""

from __future__ import annotations

import textwrap
from datetime import datetime
from typing import Dict, List, Optional

import config
from core.models import Item

WIDTH = 78


def _wrap(text: str, indent: str = "") -> str:
    if not text:
        return ""
    return textwrap.fill(
        text, width=WIDTH, initial_indent=indent, subsequent_indent=indent
    )


def _item_block(item: Item, index: int) -> List[str]:
    lines: List[str] = []
    lines.append("")
    lines.append(_wrap("{0}. {1}".format(index, item.title)))

    meta = [item.source_label, item.published_display]
    for extra in (item.phase, item.status, item.sponsor, item.nct_id):
        if extra:
            meta.append(extra)
    lines.append(_wrap("Impact {0}/5 | {1}".format(item.importance, " | ".join(meta)), "   "))

    lines.append("")
    lines.append(_wrap(item.summary, "   "))
    lines.append("")
    lines.append(_wrap("WHY IT MATTERS: {0}".format(item.why_it_matters), "   "))
    lines.append(_wrap(item.url, "   "))

    for also in item.also_reported_by:
        lines.append(_wrap("Also: {0} - {1}".format(also.get("label"), also.get("url")), "   "))

    return lines


def render(
    items: List[Item],
    editors_take: str,
    issue_number: int,
    issue_date: datetime,
    window_start: datetime,
    generated_at: Optional[datetime] = None,
    ai_enabled: bool = True,
) -> str:
    generated_at = generated_at or datetime.utcnow()
    out: List[str] = []

    out.append("=" * WIDTH)
    out.append(config.NEWSLETTER_NAME.upper())
    out.append(config.NEWSLETTER_TAGLINE)
    out.append("=" * WIDTH)
    out.append(
        "Issue {0}  |  {1} - {2}  |  {3} development{4}".format(
            issue_number,
            window_start.strftime("%d %b"),
            issue_date.strftime("%d %b %Y"),
            len(items),
            "" if len(items) == 1 else "s",
        )
    )

    if editors_take:
        out.append("")
        out.append("-" * WIDTH)
        out.append("EDITOR'S TAKE")
        out.append("-" * WIDTH)
        out.append(_wrap(editors_take))

    if not items:
        out.append("")
        out.append("-" * WIDTH)
        out.append("A QUIET WEEK IN MS")
        out.append("-" * WIDTH)
        out.append(_wrap(
            "No qualifying activity cleared our relevance and recency filters in this "
            "reporting window. All sources were polled successfully - ClinicalTrials.gov, "
            "FDA (3 feeds) and curated news - and returned nothing new for Multiple "
            "Sclerosis. Quiet weeks are normal in a single indication."
        ))
    else:
        grouped: Dict[str, List[Item]] = {c: [] for c in config.CATEGORIES}
        for item in items:
            grouped.setdefault(item.category, []).append(item)

        for category in config.CATEGORIES:
            bucket = grouped.get(category) or []
            if not bucket:
                continue
            bucket.sort(
                key=lambda i: (-i.importance, -(i.published.timestamp() if i.published else 0))
            )
            out.append("")
            out.append("-" * WIDTH)
            out.append("{0}  ({1} item{2})".format(
                category.upper(), len(bucket), "" if len(bucket) == 1 else "s"
            ))
            out.append("-" * WIDTH)
            for index, item in enumerate(bucket, start=1):
                out.extend(_item_block(item, index))

    out.append("")
    out.append("=" * WIDTH)
    provenance = (
        "Summaries, categories and impact scores generated by Google Gemini ({0})."
        .format(config.GEMINI_MODEL)
        if ai_enabled else
        "Offline mode: summaries, categories and impact scores come from deterministic "
        "rules rather than a language model."
    )
    out.append(_wrap(
        "Generated automatically from ClinicalTrials.gov API v2, three U.S. FDA RSS "
        "feeds (press releases, drugs, MedWatch), and curated news. " + provenance
    ))
    out.append(_wrap("Compiled {0} UTC.".format(generated_at.strftime("%Y-%m-%d %H:%M"))))
    out.append(_wrap(
        "This briefing summarises public information for competitive intelligence "
        "purposes and is not medical, investment or regulatory advice."
    ))
    out.append("=" * WIDTH)

    return "\n".join(out) + "\n"
